- src/app/services/data/servicesStorage.js
- src/app/services/getUserAssociatedServices.js
- test/servicesTests/servicesStorage.test.js
Add closing of connection. Remove test for checking null due to sequlize-mock not working
> Add description to object map

- database_scripts/mssql/005_User_Org_Mapping.sql
- src/app/invitations/data/invitationsStorage.js
- src/app/invitations/getInvitation.js
- src/app/invitations/getInvitationV2.js
- src/app/invitations/index.js
- src/app/services/data/servicesStorage.js
- src/infrastructure/repository/connection.js
- src/infrastructure/repository/externalIdentifiers.js
- src/infrastructure/repository/index.js
- src/infrastructure/repository/invitationExternalIdentifiers.js
- src/infrastructure/repository/invitationOrganisations.js
- src/infrastructure/repository/invitations.js
- src/infrastructure/repository/organisationAssociations.js
- src/infrastructure/repository/organisations.js
- src/infrastructure/repository/services.js
- src/infrastructure/repository/userOrganisations.js
- src/infrastructure/repository/users.js
- src/utils/deprecateMiddleware.js
- src/utils/index.js
- test/appTests/invitationTests/InvitationsStorageTests/upsert.test.js
- test/appTests/invitationTests/getInvitation.test.js
- test/utils/mocks.js
Allow users to be associated to an organisation without any permissions to services; with their role being at the organisation level rather than service
> NSA-1325 - Detach org from service mappign

- src/app/organisations/data/organisationsStorage.js
Add following information to response for user orgs:
* urn, uid and ukprn for organisations
* description for service
> NSA-1350 - Add extra information to user org response

- database_scripts/mssql/006_User_Organisation_update.sql
Parser had issue with update after adding status column
> NSA-1403 - Fix user_organisation.status schema update

- database_scripts/mssql/012_add_indexes.sql
Script IX_UserServices_UserOrg & IX_OrganisationAssociation_OrgAssType
> NSA-1647 - Add indexes

- src/app/organisations/createOrganisation.js
- src/app/organisations/data/organisationsStorage.js
Currently incorrect organisations are updated when syncing OSA orgs as SCITTs over-write their orgs for example
> NSA-1710 - Filter by category when looking for existing organisation in creation

- package-lock.json
- package.json
fix deprecated tls calls in tedious
> Updated tedious version

- package-lock.json
- src/app/organisations/data/organisationsStorage.js
- src/app/organisations/index.js
- src/app/organisations/listInvitationOrganisations.js
- src/app/organisations/listUserOrganisations.js
Added to support more performant full index in search
> NSA-1836 - List user/invitation org mappings

- package-lock.json
- src/app/organisations/data/organisationsStorage.js
- src/app/organisations/getOrganisationsAssociatedWithUser.js
- src/app/organisations/getOrganisationsAssociatedWithUserV2.js
- src/app/organisations/index.js
- src/utils/asyncHelpers.js
- src/utils/index.js
- test/appTests/organisationsTests/getOrganisationsAssociatedWithUser.test.js
also removed services from new endpoint
> NSA-1894 - Add v2 user organisations endpoint

- src/app/organisations/data/organisationsStorage.js
- src/app/organisations/listOrganisations.js
- test/appTests/organisationsTests/listOrganisations.test.js
> NSA-2507 Do not allow closed organisation

- src/app/organisations/data/organisationsStorage.js
NSA-2388 Self-Registration - Task Tracker - code review comment
> NSA-2388 Self-Registration - Task Tracker - test file

- src/app/organisations/getOrganisationByExternalId.js
> NSA-2297 get organisation by ukprn change in getOrganisationByExternalIdentifier

- src/app/overdueOrganisationRequests/overdueRequests.js
NSA-2795 Stop ServiceNow emails for escalations after the SLA is exceeded
> NSA-2795 Stop ServiceNow emails for escalations after the SLA is exceeded

- src/app/giasImport/groupCsvReader.js
- src/app/giasImport/importGroups.js
NSA-2789-more on group import with ukprn
> NSA-2789-more on group import with ukprn

- src/app/giasImport/groupCsvReader.js
- src/app/giasImport/importEstablishments.js
- src/app/giasImport/importGroups.js
NSA-2874 - take off GIAS pull changes from develop
Will take the changes after Corona form release
> NSA-2874 - take off GIAS pull changes from develop

- src/infrastructure/repository/invitations.js
Changes added to the ORM wrapper to trigger relevant logic to insert and update dates to those new columns
> PR-feature/4857-new columns to invitation_services table

- src/app/invitations/data/invitationsStorage.js
- src/app/organisations/data/organisationsStorage.js
- src/app/services/data/servicesStorage.js
seqalize upgrade need to wrap await statement with parenthesis when used with map.
> PR-NSA-4763-sql-orm-library-update

- src/app/giasImport/importAllGroupsData.js
- src/app/giasImport/importGroups.js
date string values are verified and converted before comparing two string dates
> PR-NSA-3648-date string values are verified and converted

- src/app/giasImport/importEstablishments.js
More changes done while delete or update organization.
only try to delete if the importing organization's status is "CreatedInError"
> PR-NSA-3648-GIAS-feed-Created-in-error-status

- src/app/giasImport/importAllGroupsData.js
It is the extension from the GIAS feed for organization functionality.
> NSA-5276-GIAS-Created-in-error for group data

- src/app/services/data/servicesStorage.js
- src/app/services/getAllServiceUsers.js
- src/app/services/index.js
User id argument has been added to getAllUsersOfService method.
> PR-NSA-5166-Synch of DSi users with GIAS accounts 

- src/app/giasImport/importEstablishments.js
- src/app/organisations/data/organisationsStorage.js
Tested all the cases and simplified
> PR-Feature/nsa 3648 changes jose

- src/app/giasImport/importEstablishments.js
- src/app/organisations/data/organisationsStorage.js
Created in error - latest update
Don't update the **created in error** status
Try to delete the record if no user associated with it
Delete the association record all the time but if delete org failed due to
other child records then capture the message and write into log.
And continue to the next record from the GIAS sync.
> PR-NSA-3648-created-in-error-more-improvement-v2

- src/app/giasImport/importAllGroupsData.js
- src/app/giasImport/importGroups.js
- src/infrastructure/repository/index.js
Group - Created in Error - Latest AC has been applied
removed Created in Error status.
> PR - NSA-5276-Created-in-error-groups-V112021

- src/app/giasImport/importAllGroupsData.js
updated a logger information for
clarity while seeing it at App Insights
> NSA-5276-Created-in-error-group

- src/infrastructure/repository/index.js
Jira ticket: https://dfe-secureaccess.atlassian.net/browse/NSA-5783
Added Hidden to organisation Status model
> NSA-5783 - Added hidden status to organisationStatus model

- src/app/organisations/data/organisationsStorage.js
- src/app/organisations/listOrganisations.js
- test/appTests/organisationsTests/listOrganisations.test.js
Jira ticket https://dfe-secureaccess.atlassian.net/browse/NSA-6313: 
- added sorting options for organisation list
- fixed bug - for displaying the data when it is stored with unknown category name
> NSA-6313 - Added sorting option for organisation list

- src/app/organisations/data/organisationsStorage.js
- src/app/organisations/listOrganisations.js
- test/appTests/organisationsTests/listOrganisations.test.js
Merged develop into release/1.0.21  to include https://dfe-secureaccess.atlassian.net/browse/NSA-6313 in the release
> Merge latest develop into release/1.0.21

- .vscode/launch.json
- src/app/organisations/data/organisationsStorage.js
- src/app/organisations/getOrganisationsAssociatedWithService.js
- src/utils/helperFunctions.js
- src/utils/index.js
- test/appTests/organisationsTests/getOrganisationsAssociatedWithService.test.js
Jira ticket: 
https://dfe-secureaccess.atlassian.net/browse/NSA-7274
**Changes:** 
Updates to the launch file to run on local env. 
Updates to the `GET /organisations/associated-with-service/:sid` endpoint: 
- Optimized the code and Sequelize query, enhancing the endpoint's response speed when retrieving service-linked organisations. 
- Modified the endpoint to enable filtering by organisation type and status. 
- The endpoint now also provides all linked organisation types associated with a given service.
> [NSA-7274] Filters to org search manage console

- package-lock.json
- package.json
Fixing the version so the pipeline can create release branches and tags with the right version
> Fix application version

- package-lock.json
- src/infrastructure/repository/index.js
**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7431
- fix vulnerable packages with `npm audit fix` command
- update Organisation Status model to include the associated tag colour
- https://github.com/DFE-Digital/login.dfe.manage/pull/278
> [DSI-7431] Add background colour to the status tags

- src/app/invitations/data/invitationsStorage.js
- src/app/organisations/data/organisationsStorage.js
- src/app/organisations/editOrganisation.js
- src/app/organisations/index.js
Link to ticket: [NSA-8654](https://dfe-secureaccess.atlassian.net/browse/NSA-8654)
A page in support to allow us to edit the name and address of category 008, 'other stakeholders' organisations
> [NSA-8654] Create edit org page

- package-lock.json
- src/app/overdueAllRequestsTypes/overdueRequests.js
- src/worker.js
- test/appTests/organisationsTests/getOrganisationsAssociatedWithService.test.js
Missing configuration was causing worker to fail when it was getting organisation requests.
Also ran `npm audit fix` to fix a small vulnerability and improved a little bit of the unit testing
> [NSA-9299] Fix missing configuration issue in worker
